package com.wimbledon.modelo;
// Generated Nov 17, 2016 8:50:16 PM by Hibernate Tools 4.3.1.Final


import java.util.HashSet;
import java.util.Set;

/**
 * Arbitro generated by hbm2java
 */
public class Arbitro  implements java.io.Serializable {


     private Integer arbiId;
     private String nombre;
     private String estado;
     private Integer docuId;
     private String numeroIdentificacion;
     private Set<Partido> partidos = new HashSet<Partido>(0);
     private Set<Usuarios> usuarioses = new HashSet<Usuarios>(0);

    public Arbitro() {
    }

	
    public Arbitro(Integer arbiId, String nombre, String estado, Integer docuId, String numeroIdentificacion) {
        this.arbiId = arbiId;
        this.nombre = nombre;
        this.estado = estado;
        this.docuId = docuId;
        this.numeroIdentificacion = numeroIdentificacion;
    }
    public Arbitro(Integer arbiId, String nombre, String estado, Integer docuId, String numeroIdentificacion, Set<Partido> partidos, Set<Usuarios> usuarioses) {
       this.arbiId = arbiId;
       this.nombre = nombre;
       this.estado = estado;
       this.docuId = docuId;
       this.numeroIdentificacion = numeroIdentificacion;
       this.partidos = partidos;
       this.usuarioses = usuarioses;
    }
   
    public Integer getArbiId() {
        return this.arbiId;
    }
    
    public void setArbiId(Integer arbiId) {
        this.arbiId = arbiId;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Integer getDocuId() {
        return this.docuId;
    }
    
    public void setDocuId(Integer docuId) {
        this.docuId = docuId;
    }
    public String getNumeroIdentificacion() {
        return this.numeroIdentificacion;
    }
    
    public void setNumeroIdentificacion(String numeroIdentificacion) {
        this.numeroIdentificacion = numeroIdentificacion;
    }
    public Set<Partido> getPartidos() {
        return this.partidos;
    }
    
    public void setPartidos(Set<Partido> partidos) {
        this.partidos = partidos;
    }
    public Set<Usuarios> getUsuarioses() {
        return this.usuarioses;
    }
    
    public void setUsuarioses(Set<Usuarios> usuarioses) {
        this.usuarioses = usuarioses;
    }




}


