package com.wimbledon.modelo;
// Generated Nov 17, 2016 8:50:16 PM by Hibernate Tools 4.3.1.Final


import java.util.HashSet;
import java.util.Set;

/**
 * Directortorneo generated by hbm2java
 */
public class Directortorneo  implements java.io.Serializable {


     private Integer ditoId;
     private String nombre;
     private String estado;
     private String numeroIdentificacion;
     private Set<Partido> partidos = new HashSet<Partido>(0);
     private Set<Usuarios> usuarioses = new HashSet<Usuarios>(0);

    public Directortorneo() {
    }

	
    public Directortorneo(Integer ditoId, String nombre, String estado, String numeroIdentificacion) {
        this.ditoId = ditoId;
        this.nombre = nombre;
        this.estado = estado;
        this.numeroIdentificacion = numeroIdentificacion;
    }
    public Directortorneo(Integer ditoId, String nombre, String estado, String numeroIdentificacion, Set<Partido> partidos, Set<Usuarios> usuarioses) {
       this.ditoId = ditoId;
       this.nombre = nombre;
       this.estado = estado;
       this.numeroIdentificacion = numeroIdentificacion;
       this.partidos = partidos;
       this.usuarioses = usuarioses;
    }
   
    public Integer getDitoId() {
        return this.ditoId;
    }
    
    public void setDitoId(Integer ditoId) {
        this.ditoId = ditoId;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
   
    public String getNumeroIdentificacion() {
        return this.numeroIdentificacion;
    }
    
    public void setNumeroIdentificacion(String numeroIdentificacion) {
        this.numeroIdentificacion = numeroIdentificacion;
    }
    public Set<Partido> getPartidos() {
        return this.partidos;
    }
    
    public void setPartidos(Set<Partido> partidos) {
        this.partidos = partidos;
    }
    public Set<Usuarios> getUsuarioses() {
        return this.usuarioses;
    }
    
    public void setUsuarioses(Set<Usuarios> usuarioses) {
        this.usuarioses = usuarioses;
    }




}


