package com.wimbledon.modelo;
// Generated Nov 17, 2016 8:50:16 PM by Hibernate Tools 4.3.1.Final


import java.util.HashSet;
import java.util.Set;

/**
 * Jugador generated by hbm2java
 */
public class Jugador  implements java.io.Serializable {


     private Integer jugaId;
     private String nombre;
     private String estado;
     private Integer ranking;
     private Integer hombre;
     private String numeroIdentificacion;
     private Set<Partido> partidosForJugaaId = new HashSet<Partido>(0);
     private Set<Partido> partidosForJugabId = new HashSet<Partido>(0);

    public Jugador() {
    }

	
    public Jugador(Integer jugaId, String nombre, String estado, Integer hombre, String numeroIdentificacion) {
        this.jugaId = jugaId;
        this.nombre = nombre;
        this.estado = estado;
        this.hombre = hombre;
        this.numeroIdentificacion = numeroIdentificacion;
    }
    public Jugador(Integer jugaId, String nombre, String estado, Integer ranking, Integer hombre, String numeroIdentificacion, Set<Partido> partidosForJugaaId, Set<Partido> partidosForJugabId) {
       this.jugaId = jugaId;
       this.nombre = nombre;
       this.estado = estado;
       this.ranking = ranking;
       this.hombre = hombre;
       this.numeroIdentificacion = numeroIdentificacion;
       this.partidosForJugaaId = partidosForJugaaId;
       this.partidosForJugabId = partidosForJugabId;
    }
   
    public Integer getJugaId() {
        return this.jugaId;
    }
    
    public void setJugaId(Integer jugaId) {
        this.jugaId = jugaId;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Integer getRanking() {
        return this.ranking;
    }
    
    public void setRanking(Integer ranking) {
        this.ranking = ranking;
    }
    public Integer getHombre() {
        return this.hombre;
    }
    
    public void setHombre(Integer hombre) {
        this.hombre = hombre;
    }
    public String getNumeroIdentificacion() {
        return this.numeroIdentificacion;
    }
    
    public void setNumeroIdentificacion(String numeroIdentificacion) {
        this.numeroIdentificacion = numeroIdentificacion;
    }
    public Set<Partido> getPartidosForJugaaId() {
        return this.partidosForJugaaId;
    }
    
    public void setPartidosForJugaaId(Set<Partido> partidosForJugaaId) {
        this.partidosForJugaaId = partidosForJugaaId;
    }
    public Set<Partido> getPartidosForJugabId() {
        return this.partidosForJugabId;
    }
    
    public void setPartidosForJugabId(Set<Partido> partidosForJugabId) {
        this.partidosForJugabId = partidosForJugabId;
    }




}


