package com.wimbledon.modelo;
// Generated Nov 17, 2016 8:50:16 PM by Hibernate Tools 4.3.1.Final


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Partido generated by hbm2java
 */
public class Partido  implements java.io.Serializable {


     private Integer partId;
     private Arbitro arbitro;
     private Cancha cancha;
     private Directortorneo directortorneo;
     private Jugador jugadorByJugaaId;
     private Jugador jugadorByJugabId;
     private Tipopartido tipopartido;
     private Torneo torneo;
     private Date hora;
     private Integer tiempototal;
     private String estado;
     private Set<Sett> setts = new HashSet<Sett>(0);

    public Partido() {
    }

	
    public Partido(Integer partId, Arbitro arbitro, Cancha cancha, Directortorneo directortorneo, Jugador jugadorByJugaaId, Jugador jugadorByJugabId, Tipopartido tipopartido, Torneo torneo, Date hora, String estado) {
        this.partId = partId;
        this.arbitro = arbitro;
        this.cancha = cancha;
        this.directortorneo = directortorneo;
        this.jugadorByJugaaId = jugadorByJugaaId;
        this.jugadorByJugabId = jugadorByJugabId;
        this.tipopartido = tipopartido;
        this.torneo = torneo;
        this.hora = hora;
        this.estado = estado;
    }
    public Partido(Integer partId, Arbitro arbitro, Cancha cancha, Directortorneo directortorneo, Jugador jugadorByJugaaId, Jugador jugadorByJugabId, Tipopartido tipopartido, Torneo torneo, Date hora, Integer tiempototal, String estado, Set<Sett> setts) {
       this.partId = partId;
       this.arbitro = arbitro;
       this.cancha = cancha;
       this.directortorneo = directortorneo;
       this.jugadorByJugaaId = jugadorByJugaaId;
       this.jugadorByJugabId = jugadorByJugabId;
       this.tipopartido = tipopartido;
       this.torneo = torneo;
       this.hora = hora;
       this.tiempototal = tiempototal;
       this.estado = estado;
       this.setts = setts;
    }
   
    public Integer getPartId() {
        return this.partId;
    }
    
    public void setPartId(Integer partId) {
        this.partId = partId;
    }
    public Arbitro getArbitro() {
        return this.arbitro;
    }
    
    public void setArbitro(Arbitro arbitro) {
        this.arbitro = arbitro;
    }
    public Cancha getCancha() {
        return this.cancha;
    }
    
    public void setCancha(Cancha cancha) {
        this.cancha = cancha;
    }
    public Directortorneo getDirectortorneo() {
        return this.directortorneo;
    }
    
    public void setDirectortorneo(Directortorneo directortorneo) {
        this.directortorneo = directortorneo;
    }
    public Jugador getJugadorByJugaaId() {
        return this.jugadorByJugaaId;
    }
    
    public void setJugadorByJugaaId(Jugador jugadorByJugaaId) {
        this.jugadorByJugaaId = jugadorByJugaaId;
    }
    public Jugador getJugadorByJugabId() {
        return this.jugadorByJugabId;
    }
    
    public void setJugadorByJugabId(Jugador jugadorByJugabId) {
        this.jugadorByJugabId = jugadorByJugabId;
    }
    public Tipopartido getTipopartido() {
        return this.tipopartido;
    }
    
    public void setTipopartido(Tipopartido tipopartido) {
        this.tipopartido = tipopartido;
    }
    public Torneo getTorneo() {
        return this.torneo;
    }
    
    public void setTorneo(Torneo torneo) {
        this.torneo = torneo;
    }
    public Date getHora() {
        return this.hora;
    }
    
    public void setHora(Date hora) {
        this.hora = hora;
    }
    public Integer getTiempototal() {
        return this.tiempototal;
    }
    
    public void setTiempototal(Integer tiempototal) {
        this.tiempototal = tiempototal;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    
    public Set<Sett> getSetts() {
        return this.setts;
    }
    
    public void setSetts(Set<Sett> setts) {
        this.setts = setts;
    }




}


