package com.wimbledon.modelo;
// Generated Nov 17, 2016 8:50:16 PM by Hibernate Tools 4.3.1.Final



/**
 * Sett generated by hbm2java
 */
public class Sett  implements java.io.Serializable {


     private Integer setId;
     private Partido partido;
     private Integer gamejugador1;
     private Integer gamejugador2;
     private Double tiempo;
     private String estado;

    public Sett() {
    }

    public Sett(Integer setId, Partido partido, Integer gamejugador1, Integer gamejugador2, Double tiempo, String estado) {
       this.setId = setId;
       this.partido = partido;
       this.gamejugador1 = gamejugador1;
       this.gamejugador2 = gamejugador2;
       this.tiempo = tiempo;
       this.estado = estado;
    }
   
    public Integer getSetId() {
        return this.setId;
    }
    
    public void setSetId(Integer setId) {
        this.setId = setId;
    }
    public Partido getPartido() {
        return this.partido;
    }
    
    public void setPartido(Partido partido) {
        this.partido = partido;
    }
    public Integer getGamejugador1() {
        return this.gamejugador1;
    }
    
    public void setGamejugador1(Integer gamejugador1) {
        this.gamejugador1 = gamejugador1;
    }
    public Integer getGamejugador2() {
        return this.gamejugador2;
    }
    
    public void setGamejugador2(Integer gamejugador2) {
        this.gamejugador2 = gamejugador2;
    }
    public Double getTiempo() {
        return this.tiempo;
    }
    
    public void setTiempo(Double tiempo) {
        this.tiempo = tiempo;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }




}


