package com.wimbledon.modelo;
// Generated Nov 17, 2016 8:50:16 PM by Hibernate Tools 4.3.1.Final


import java.util.HashSet;
import java.util.Set;

/**
 * Tipopartido generated by hbm2java
 */
public class Tipopartido  implements java.io.Serializable {


     private Integer tipaId;
     private String nombre;
     private String estado;
     private Set<Partido> partidos = new HashSet<Partido>(0);

    public Tipopartido() {
    }

	
    public Tipopartido(Integer tipaId, String nombre, String estado) {
        this.tipaId = tipaId;
        this.nombre = nombre;
        this.estado = estado;
    }
    public Tipopartido(Integer tipaId, String nombre, String estado, Set<Partido> partidos) {
       this.tipaId = tipaId;
       this.nombre = nombre;
       this.estado = estado;
       this.partidos = partidos;
    }
   
    public Integer getTipaId() {
        return this.tipaId;
    }
    
    public void setTipaId(Integer tipaId) {
        this.tipaId = tipaId;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Set<Partido> getPartidos() {
        return this.partidos;
    }
    
    public void setPartidos(Set<Partido> partidos) {
        this.partidos = partidos;
    }




}


