package com.wimbledon.modelo;
// Generated Nov 17, 2016 8:50:16 PM by Hibernate Tools 4.3.1.Final



/**
 * Usuarios generated by hbm2java
 */
public class Usuarios  implements java.io.Serializable {


     private Integer usuaId;
     private Arbitro arbitro;
     private Directortorneo directortorneo;
     private String login;
     private String password;

    public Usuarios() {
    }

    public Usuarios(Integer usuaId, Arbitro arbitro, Directortorneo directortorneo, String login, String password) {
       this.usuaId = usuaId;
       this.arbitro = arbitro;
       this.directortorneo = directortorneo;
       this.login = login;
       this.password = password;
    }
   
    public Integer getUsuaId() {
        return this.usuaId;
    }
    
    public void setUsuaId(Integer usuaId) {
        this.usuaId = usuaId;
    }
    public Arbitro getArbitro() {
        return this.arbitro;
    }
    
    public void setArbitro(Arbitro arbitro) {
        this.arbitro = arbitro;
    }
    public Directortorneo getDirectortorneo() {
        return this.directortorneo;
    }
    
    public void setDirectortorneo(Directortorneo directortorneo) {
        this.directortorneo = directortorneo;
    }
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


